/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

import Datos.Empleado;
import Datos.Empresa;

/**
 *
 * @author 203P27
 */
public class Administrador extends javax.swing.JFrame {

    private Empresa email;
    private int usuarioValidado;
//agregamos los paneles
    PanelAltaUsuario palta;
    PanelModificaciones pmodifi;

    /**
     * Constructor que recibe los empleados y el usuario validado
     * @param email
     * @param usuarioValidado
     */
    public Administrador(Empresa email, int usuarioValidado) {
        this.email = email;
        this.usuarioValidado = usuarioValidado;
        initComponents();
        setSize(500, 301);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuNuevoUsuario = new javax.swing.JMenuItem();
        mnuModificarUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuDesconectar = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jMenu1.setText("Usuarios");

        mnuNuevoUsuario.setText("Nuevo Usuario");
        mnuNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevoUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(mnuNuevoUsuario);

        mnuModificarUsuario.setText("Modificar Usuario");
        mnuModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuModificarUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(mnuModificarUsuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        mnuDesconectar.setText("Desconectar");
        mnuDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDesconectarActionPerformed(evt);
            }
        });
        jMenu2.add(mnuDesconectar);

        mnuSalir.setText("Salir de la Aplicacion");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu2.add(mnuSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuModificarUsuarioActionPerformed
        // TODO add your handling code here:

        quitarPaneles();
        //se crea la pantalla
        pmodifi = new PanelModificaciones(email);
        this.add(pmodifi);//hay que insertar un Flow Layout para que te salga la ventana
        pack();
    }//GEN-LAST:event_mnuModificarUsuarioActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        dispose();
        pack();
        System.exit(0);//sale del programa
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDesconectarActionPerformed
        // TODO add your handling code here:
        new Validacion(email).setVisible(true);//se va a la ventana Validacion y le se le pasa la empresa
        dispose();
        pack();
    }//GEN-LAST:event_mnuDesconectarActionPerformed

    private void mnuNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevoUsuarioActionPerformed
        // TODO add your handling code here:
        quitarPaneles();
        //se crea la pantalla
        palta = new PanelAltaUsuario(email);
        this.add(palta);//hay que insertar un Flow Layout para que te salga la ventana
        pack();
    }//GEN-LAST:event_mnuNuevoUsuarioActionPerformed
    
    /**
     * Metodo para eliminar los paneles
     */
    private void quitarPaneles() {

        try {
            this.email = palta.email;//el email de la clase administrador es igual al email del panel de alta(antes de destruirlo)
            remove(palta);
        } catch (Exception e) {

        }
        try {
            remove(pmodifi);
        } catch (Exception e) {

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuDesconectar;
    private javax.swing.JMenuItem mnuModificarUsuario;
    private javax.swing.JMenuItem mnuNuevoUsuario;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables
}
